#include "Arduino.h"

String runHtml = "<!DOCTYPE html><head"
   "> <meta name=\"viewp"
   "ort\" content=\"widt"
   "h=device-width, init"
   "ial-scale=1.0\"/> <m"
   "eta charset=\"UTF-8"
   "\"> <link rel=\"styl"
   "esheet\" href=\"styl"
   "e.css\" type=\"text/"
   "css\"></head><body o"
   "nload=\"loadPayloadT"
   "ables()\"> <script s"
   "rc=\"run.js\"> </scr"
   "ipt> <div class=\"st"
   "atus\"></div><nav> <"
   "a href=\"\">Run</a> "
   "<a href=\"help.html"
   "\">Help</a> </nav> <"
   "div class=\"containe"
   "r\"> <div class=\"pa"
   "yloadTable\"> <h2>St"
   "arred</h2> <table> <"
   "tbody id=\"tableStar"
   "red\"> </tbody> </ta"
   "ble> <div id=\"editS"
   "tarred\"> </div></di"
   "v><div class=\"paylo"
   "adTable\"> <h2>Linux"
   "</h2> <table> <thead"
   "> </thead> <tbody id"
   "=\"tableLinux\"> </t"
   "body> </table> <div "
   "id=\"editLinux\"> </"
   "div></div><div class"
   "=\"payloadTable\"> <"
   "h2>Mac</h2> <table> "
   "<thead> </thead> <tb"
   "ody id=\"tableMac\">"
   " </tbody> </table> <"
   "div id=\"editMac\"> "
   "</div></div><div cla"
   "ss=\"payloadTable\">"
   " <h2>Windows</h2> <t"
   "able> <thead> </thea"
   "d> <tbody id=\"table"
   "Windows\"> </tbody> "
   "</table> <div id=\"e"
   "ditWindows\"> </div>"
   "</div></div></body><"
   "/html>";

String runJs="function loadPayloadTables(){console.log(\"Loading payloads...\");const e=new XMLHttpRequest;e.open(\"GET\",\"/data.json?rand=\"+Date.now(),!1),e.send(null);var t=e.responseText;const n=JSON.parse(t),a=[\"tableStarred\",\"tableLinux\",\"tableMac\",\"tableWindows\"],d=[\"Starred\",\"Linux\",\"Mac\",\"Windows\"],o=[\"editStarred\",\"editLinux\",\"editMac\",\"editWindows\"];for(let e=0;e<4;e++)for(let t=0;t<Object.keys(n).length;t++)try{var i=n[t];if(i.pOS.toUpperCase()==d[e].toUpperCase()){const t=document.createElement(\"tr\"),n=document.createElement(\"td\");n.innerText=i.pName,n.classList.add(\"payloadname\");const l=document.createElement(\"td\");l.innerHTML=\'<button class=\"edit\" onclick=\"editPayload(\\\'/\'+d[e]+\"/\"+i.pCategory+\"/\"+i.pName+\"\',\'\"+o[e]+\"\')\\\">Edit</button>\";const s=document.createElement(\"td\");s.innerHTML=\'<button class=\"run\" onclick=\"runPayload(\\\'\'+o[e]+\"\',\'/\"+d[e]+\"/\"+i.pCategory+\"/\"+i.pName+\"\')\\\">Run</button>\",t.appendChild(n),t.appendChild(l),t.appendChild(s),document.getElementById(a[e]).appendChild(t)}}catch(e){break}}function runPayload(e,t){closeEdit(),document.getElementById(e).innerHTML=\'<p id=\"statusText\">Running: <b>\'+t+\"</b></p>\";var n=new XMLHttpRequest;return n.open(\"GET\",\"runpayload.php?path=\"+t,!1),n.send(null),n.responseText}function editPayload(e,t){closeEdit();var n=document.getElementById(t),a=new XMLHttpRequest;a.open(\"GET\",\"getpayload.php?path=\"+e,!1),a.send(null),n.innerHTML=\'<p id=\"statusText\">Editing: <b>\'+e+\'</b></p><div class=\"row\"> <div class=\"input-field col s12\"> <textarea id=\"textarea1\" rows = 10 class=\"materialize-textarea\">\'+atob(a.responseText)+\'\\n</textarea> </div> <button class=\"run\" onclick=\"runLive(\\\'\'+t+\'\\\')\">Run Live</button> <button class=\"edit\" onclick=\"savePayload(\\\'\'+t+\"\',\'\"+e+\"\')\\\">Save</button> </div> \"}function closeEdit(e){document.getElementById(\"editStarred\").innerHTML=\"\",document.getElementById(\"editLinux\").innerHTML=\"\",document.getElementById(\"editMac\").innerHTML=\"\",document.getElementById(\"editWindows\").innerHTML=\"\"}function runLive(e){document.getElementById(\"statusText\").innerHTML=\"<p><b>Running Live!</b></p>\";document.getElementById(textarea1);var t=new XMLHttpRequest;t.open(\"POST\",\"runlive.php\"),t.setRequestHeader(\"Content-Type\",\"plain/text\"),t.send(btoa(document.getElementById(\"textarea1\").value))}function savePayload(e,t){document.getElementById(\"statusText\").innerHTML=\"<p>Saved: <b>\"+t+\"</b></p>\";document.getElementById(textarea1);var n=new XMLHttpRequest;n.open(\"POST\",\"savepayload.php\"),n.setRequestHeader(\"Content-Type\",\"application/x-www-form-urlencoded\"),n.send(\"path=\"+t+\"&content=\"+btoa(textarea1.value))}";

String runCss = "*{font-family: sans-"
   "serif;}.container{wi"
   "dth: 70%; margin: au"
   "to;}table{width: 100"
   "%; padding: .7em;}tr"
   "{text-align: left;}t"
   "d{padding: .3em;}.pa"
   "yloadTable{margin-bo"
   "ttom: 4em;}button{bo"
   "rder: none; padding:"
   " .8em; border-radius"
   ": 3px;}.run{backgrou"
   "nd-color: #ef5350; c"
   "olor: white;}.run:ho"
   "ver{background-color"
   ": #e57373;}.edit{bac"
   "kground-color: #66bb"
   "6a73; color: white;}"
   ".edit:hover{backgrou"
   "nd-color: #8abe8d91;"
   "}textarea{display: b"
   "lock; width: 100%; m"
   "ax-width:100%; min-w"
   "idth: 100%; margin-b"
   "ottom: 1em; backgrou"
   "nd-color: #263238; c"
   "olor: white; padding"
   ": .7em; box-sizing: "
   "border-box;}nav{max-"
   "width: 100%; padding"
   ": 0 2em; background-"
   "color: #263238;}tabl"
   "e, textarea{border-r"
   "adius: 5px; backgrou"
   "nd-color: #263238; b"
   "order: 1px solid #25"
   "282c;}nav a{display:"
   " inline-block; paddi"
   "ng: .9em; color: #e4"
   "e4e4; text-decoratio"
   "n: none;}nav a:hover"
   "{background-color: #"
   "222529; cursor: poin"
   "ter;}td{width: 200px"
   " !important;}body{ma"
   "rgin: 0; background-"
   "color: #36393e; colo"
   "r: #e4e4e4;}.payload"
   "name{width: 300px !i"
   "mportant;}#editStarr"
   "ed, #editLinux, #edi"
   "tWindows, #editMac{m"
   "argin-top: 2em;}";
