name: RubberNugget CI

on:
  push:
    branches: [ main, bp-dev ]
    paths: [ "src/**" ]
  pull_request:
    branches: [ main, bp-dev ]
    paths: [ "src/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd src
        docker build . --file Dockerfile --tag rubber-nugget:$(date +%s)

